### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by jwohlfeil** [LennyN95/weboutline#1]
1. Weboutline Tab is opened on the left http://take.ms/kvzNk 
2. I opened a new empty tab with Plain Text Syntax and started to search an replace a string
3. Then the error occurse every time, that new tab gets focused.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.2
**Thrown From**: [weboutline](https://github.com/LennyN95/weboutline) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/jw/.atom/packages/weboutline/lib/weboutline-view.js:114

TypeError: Cannot read property 'path' of null
    at WeboutlineView.parseFile (/packages/weboutline/lib/weboutline-view.js:114:34)
    at /packages/weboutline/lib/weboutline-view.js:65:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:262:18)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1002:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -0:38.2.0 find-and-replace:show (input.hidden-input)
     -0:37.2.0 find-and-replace:focus-next (input.hidden-input)
     -0:36.7.0 core:select-all (input.hidden-input)
     -0:36.5.0 core:paste (input.hidden-input)
     -0:35.7.0 find-and-replace:focus-next (input.hidden-input)
     -0:35 core:confirm (input.hidden-input)
     -0:30 core:copy (input.hidden-input)
  2x -0:26.2.0 core:paste (input.hidden-input)
     -0:18.9.0 core:select-all (input.hidden-input)
     -0:18.1.0 core:cut (input.hidden-input)
     -0:13.6.0 core:paste (input.hidden-input)
     -0:11.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:11 editor:select-to-end-of-word (input.hidden-input)
     -0:10.4.0 core:paste (input.hidden-input)
     -0:07.1.0 core:save (input.hidden-input)
     -0:02.3.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
open-project-in-tower 1.4.0 
atom-terminal 0.8.0 
atom-wrap-in-tag 0.6.0 
atom-zurb-foundation 2.1.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-project-paths 2.2.0 
busy-signal 1.4.3 
codekit-commands 1.3.3 
docblockr 0.13.6 
docs-snippets 0.8.0 
doxygen-snippets 0.1.1 
file-icons 2.1.16 
flex-tool-bar 0.15.1 
foundation5-snippets 0.2.2 
git-plus 7.10.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-entities 0.4.0 
hyperclick 0.1.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-applescript 0.3.0 
language-doxygen 0.3.0 
language-htaccess 0.2.0 
language-markdown 0.25.1 
language-smarty 1.8.0 
language-twig 1.6.3 
language-typoscript2 1.4.0 
line-ending-converter 1.3.2 
lines 0.13.1 
linter 2.2.0 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-git-diff 4.3.1 
open-file-in 1.2.3 
open-recent 5.0.0 
package-cop 0.2.10 
package-list 0.1.2 
pigments 0.40.2 
sort-lines 0.18.0 
svg-preview 0.12.1 
svgo 3.0.0 
symbols-tree-view 0.14.0 
tool-bar 1.1.6 
tree-view-autoresize 2.3.0 
typo3 0.7.0 
typo3-fluid-atom-snippets 1.4.0 
uniq-line 0.0.2 
url-encode 0.5.0 
weboutline 0.6.0 
wordpress-dictionary 4.4.0 
xml-formatter 0.11.0 
```

**Comment by LennyN95** [comment]
Thanks for your error report.
I fixed the issue, all you have to do is to update weboutline to 0.6.1.
Please note that weboutline is only provided for those files who are saved to the file system.

Best regards
Leonard Nürnberg
